### ISSUE TITLE
Training with Aerial dataset and issue with the metric

### ISSUE THREAD

**Issue by hmchuong** [chenwydj/ultra_high_resolution_segmentation#21]
Thanks for your appreciate work!
I'm trying to run your code on Aerial dataset but I have found some troubles with this kind of foreground-background imbalance data.
1. Should the number of classes be 1 or 2? If it's 1, I need to change the foreground pixel in the label to 0 and the background pixel to 1, isn't it?
2. In the metrcics.py, I found that you use the mask to remove the background. However, I realized that if my prediction for the foreground is full of the image, I can easily get the mIoU of 100%. The reason is that there is only one class here and the mask will affect the accuracy of the class.

Thank you and waiting for your response.

**Comment by chenwydj** [comment]
Hi @hmchuong! Thank you for your interest!

1. The number of classes should be two. You can keep the foreground as 1 and background as 0.
2. For the mask, are you talking about [this line](https://github.com/TAMU-VITA/GLNet/blob/master/utils/metrics.py#L17)? The mask here only filters out classes to be ignored, which should not affect your measurement here. If you do have an image with all pixels as foreground, yes you may get 100% IoU, but the overall accuracy will be average over the whole dataset.

Hope that helps!

**Comment by hmchuong** [comment]
Thanks for your response,
I got the mIoU as 0.68 after retraining. However, the prediction mask on the Aerial dataset is not good

**Prediction**
![chicago1_mask](https://user-images.githubusercontent.com/15813059/70884415-903d8700-2008-11ea-9b04-f09ec19b7bd8.png)
**Groundtruth**
![chicago1](https://user-images.githubusercontent.com/15813059/70884483-ba8f4480-2008-11ea-9caf-64e5d228ef19.png)

Would you mind sharing your weight so that I can evaluate and compare it with mine?

**Comment by chenwydj** [comment]
Due to the time being I may not be able to clean the weight files for the Inria dataset.

Is your result from both the global and local branch? (i.e. mode = 3)

**Comment by hmchuong** [comment]
> Due to the time being I may not be able to clean the weight files for the Inria dataset.
> 
> Is your result from both the global and local branch? (i.e. mode = 3)

Yes, the mode =3.

**Comment by chenwydj** [comment]
We used `size_g = size_p = 536` in our experiments for Inria. Maybe `508` is small which may cause loss of details on the boundaries of patches.

**Comment by hmchuong** [comment]
Ok, let's I try this.
Thank you

**Comment by chenwydj** [comment]
Also, you may want to check the intermediate results from the global branch. Though it may not be good, it should predict at least major building areas, leaving only some minor ones.
