### ISSUE TITLE
preprocess for dataset

### ISSUE THREAD

**Issue by GeneralLi95** [chenwydj/ultra_high_resolution_segmentation#22]
Hi, thanks for your excellent job.

I just want to know how do you split your dataset, especially 
> put the image and label files into folder "train" and folder "crossvali"

Do you write a script to do this or put it manually

**Comment by chenwydj** [comment]
You can put the images into splits according to the file names: [train](https://github.com/TAMU-VITA/GLNet/blob/master/train.txt), [val](https://github.com/TAMU-VITA/GLNet/blob/master/crossvali.txt), [test](https://github.com/TAMU-VITA/GLNet/blob/master/test.txt).

**Comment by GeneralLi95** [comment]
Thank you. @chenwydj  I see the 'txt' files.  Is there any script that can help move the files automaticlly ?

**Comment by chenwydj** [comment]
Sorry we did not write this script. A short Python script should not be difficult.

**Comment by GeneralLi95** [comment]
@chenwydj  OK. Copy that. Thank you again. I will try to write one.
