### ISSUE TITLE
Testing and validation filenames of Inria Aerial Dataset

### ISSUE THREAD

**Issue by hmchuong** [chenwydj/ultra_high_resolution_segmentation#24]
Hi, I'm working to reproduce your result, could you please give me the list of filenames of testing and validation subsets

**Comment by chenwydj** [comment]
Hi @hmchuong !

Train: https://drive.google.com/open?id=1jWvyRRF3HP6YEmaf3YSPcG8_b3_EoJQ1
Validation: https://drive.google.com/open?id=1qLLM-wBEu8viigRtA0-yYNKSPJXel-nq
Test: https://drive.google.com/open?id=1ezaeray1ZsbWGDOlI35EA9eHhTVm2dQc

**Comment by hmchuong** [comment]
Thank you!
