### ISSUE TITLE
跑第一阶段时报错

### ISSUE THREAD

**Issue by xxx0320** [chenwydj/ultra_high_resolution_segmentation#29]
作者大大能帮忙看看嘛？
标记图片为三通道，我自己改成了单通道，但是之后一直报错。
Traceback (most recent call last):
  File "train_deep_globe.py", line 104, in <module>
    loss = trainer.train(sample_batched, model, global_fixed)
  File "/home/pbc/project/GLNet-master/helper.py", line 306, in train
    loss = self.criterion(outputs_global, labels_glb)
  File "train_deep_globe.py", line 84, in <lambda>
    criterion = lambda x,y: criterion1(x, y)
  File "/home/pbc/anaconda3/envs/pt11/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pbc/project/GLNet-master/utils/loss.py", line 56, in forward
    if self.one_hot: target = one_hot(target, input.size(1))
  File "/home/pbc/project/GLNet-master/utils/loss.py", line 31, in one_hot
    return mask.scatter_(1, index, ones)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorScatterGather.cu:380

**Comment by xxx0320** [comment]
/pytorch/aten/src/THC/THCTensorScatterGather.cu:188: void THCudaTensor_scatterFillKernel(TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, Real, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [83,0,0], thread: [414,0,0] Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed.
/pytorch/aten/src/THC/THCTensorScatterGather.cu:188: void THCudaTensor_scatterFillKernel(TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, Real, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [83,0,0], thread: [415,0,0] Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed.

**Comment by chenwydj** [comment]
Hi @xxx0320! Thank you for your interest in our work!

This error usually happens when the int value in your ground truth is greater than your output dimension. For example, assuming your output channel is 6 (i.e. 6 semantic classes for segmentation), but your ground truth files contains a value >= 6.
