### ISSUE TITLE
Is GLNet suitable for small size images?

### ISSUE THREAD

**Issue by dagongji10** [chenwydj/ultra_high_resolution_segmentation#30]
@chenwydj 
I have test it on GlobeLandCover dataset. The image size is 2448\*2448, but my data image is 256\*256.
I wonder if GLNet also work on small size image?
Or if I want to make it work better on my own dataset, what changes can I do?
Do you have any suggestions?

**Comment by chenwydj** [comment]
Hi @dagongji10! Thank you for your interest in our work!

We did not test our work on small images like 256*256. You may still try with our patch-based method, by using a crop size smaller than 256.

**Comment by dagongji10** [comment]
> Hi @dagongji10! Thank you for your interest in our work!
> 
> We did not test our work on small images like 256*256. You may still try with our patch-based method, by using a crop size smaller than 256.

Thanks for reply! 

I have trained `fpn_deepglobe_global.pth` use size_g=size_p=112, it runs normally. But when I train `fpn_deepglobe_global2local.pth`, I got error :
```RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 16 and 8 in dimension 2 at ../aten/src/TH/generic/THTensor.cpp: 711```
I guess the reason is my input image is (256, 256) not (2448, 2448), the feature_map size come to 0 after downsampling in the middle. 

And what do you mean `patch-based method`? Must I train all the 3 model: fpn_deep_globe_global, fpn_deep_globe_global2local, fpn_deep_globe_local2global ? Or only train one of them for small size image is enough?
