### ISSUE TITLE
Coarse-to-Fine GLNet

### ISSUE THREAD

**Issue by cloudyliy** [chenwydj/ultra_high_resolution_segmentation#31]
Is there any coarse-to-fine GLNet code here?

**Comment by chenwydj** [comment]
Hi @cloudyliy ! We currently don't have time to include coarse-to-fine GLNet for binary segmentation in this repo.

**Comment by cloudyliy** [comment]
Hello, I recently wanted to try coarse to fine GLNet on an imbalanced data set. Is it convenient to learn from this part of the code? My email is liyun_zhang@foxmail.com, thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wuyang"<notifications@github.com&gt;; 
发送时间: 2020年10月24日(星期六) 上午10:08
收件人: "VITA-Group/GLNet"<GLNet@noreply.github.com&gt;; 
抄送: "LIY"<2659678835@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [VITA-Group/GLNet] Coarse-to-Fine GLNet (#31)





 
Hi @cloudyliy ! We currently don't have time to include coarse-to-fine GLNet for binary segmentation in this repo.

**Comment by chenwydj** [comment]
Hi @cloudyliy !

The basic idea of coarse-to-fine GLNet is to crop the foreground out of the background using the prediction from the global branch, and the local branch will use the cropped foreground. Note that this strategy is specialized for binary segmentation for now.
