### ISSUE TITLE
Training of Local Network is extremely slow!

### ISSUE THREAD

**Issue by rushin682** [chenwydj/ultra_high_resolution_segmentation#32]
Hi, I'm trying to train the local network i.e mode 2, however the training is extremely slow. 
It take ~2.5 hours to complete 1 epoch of training.

Is that normal?

Please let me know soon. 

Your research is wonderful. Great work.

**Comment by chenwydj** [comment]
Hi @rushin682,

Thank you very much for your interest in our work!

The speed of our work also depends on CPU and CPU memory. Maybe you could check the workload of CPU threads and CPU memory usage.
